(TeX-add-style-hook "previewBook"
 (lambda ()
    (LaTeX-add-bibliographies
     "AndyRefs_alphabetized")
    (LaTeX-add-labels
     "chapt.intro"
     "chapt.poisson"
     "chapt.gof"
     "chapt.covariates"
     "chapt.open")
    (TeX-add-symbols
     "R"
     "bugs"
     "jags"
     "secr"
     "scrbook")
    (TeX-run-style-hooks
     "url"
     "bm"
     "makeidx"
     "color"
     "soul"
     "verbatim"
     "hyperref"
     "natbib"
     "lineno"
     "graphicx"
     "amsfonts"
     "amsmath"
     "float"
     "elsst-book"
     "latex2e"
     "bk10"
     "book"
     "Ch2/Ch2"
     "Ch3/Ch3"
     "Ch4/Chapter4"
     "Ch5/Ch5"
     "Ch6/Chapter6"
     "Ch10/Ch10"
     "Ch11/Ch11"
     "Ch14/Ch14"
     "Ch17/Ch17")))

